{% set name = "fastapi-third-party-auth" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01afc17ca5c6b0a80782805aa5cfdedbae3b26db52d47e1a5d87a50e9e1ae44a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - cryptography >=3.4.0
    - fastapi >=0.61.0
    - pydantic >=1.6.1
    - cachetools >=4.1.1
    - requests >=2.24.0
    - python-jose >=3.2.0

test:
  imports:
    - fastapi_third_party_auth
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/aiwizo/fastapi-third-party-auth
  summary: Simple library for using a third party authentication service like Keycloak or Auth0 with FastAPI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - antarcticrainforest
